# Generated by Django 4.0.8 on 2022-11-27 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0002_gamsung_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamsung',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gamsung',
            name='contents',
            field=models.TextField(verbose_name='컨텐츠내용'),
        ),
        migrations.AlterField(
            model_name='gamsung',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일자'),
        ),
        migrations.AlterField(
            model_name='gamsung',
            name='subject',
            field=models.CharField(max_length=50, verbose_name='제목'),
        ),
        migrations.AlterField(
            model_name='gamsung',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='업데이트일자'),
        ),
    ]
